server:
  context-path: /esb
  port: 9080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ibox
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update